KDUMP_VERBOSE=11
KDUMP_SAVEDIR="sftp://user:password@192.168.1.1/"
KDUMP_PRESCRIPT="cat /proc/mounts; ip a l; ls -l /proc/vmcore"
KDUMP_COMMANDLINE_APPEND="ifname=kdump:12:34:56:78:9A:BC ip=192.168.1.2::255.255.255.0:host:kdump"
MAKEDUMPFILE_OPTIONS="/proc/kcore #"
KDUMP_HOST_KEY="*"
